notifications:
  email: false

language: go

# use container infrastructure
sudo: false

# cache go build cache and pkg mod
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

go:
  - "1.12.x"

# only build commits/PRs targeted to the master branch
# this avoids duplicate builds for push + PR
branches:
  only:
    - master

# have an empty install to avoid travis doing a go get
install:
  - go get golang.org/x/tools/cmd/goimports
  - go get honnef.co/go/tools/cmd/staticcheck

script:
  - make fmt && git diff --exit-code
  - make imports && git diff --exit-code
  - make test
  - make static-check
