notifications:
  email: false

language: go

# use container infrastructure
sudo: false

# cache go build cache and pkg mod
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

go:
  - "1.15.x"

# only build commits/PRs targeted to the master branch
# this avoids duplicate builds for push + PR
branches:
  only:
    - master

install:
  - GO111MODULE=off go get golang.org/x/tools/cmd/goimports
  - GO111MODULE=off go get honnef.co/go/tools/cmd/staticcheck

script:
  - make fmt && git diff --exit-code
  - make imports && git diff --exit-code
  - make test
  - make static-check
