##
## Regular prometheus configuration
##
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
- "*rule"

# Alerting specifies settings related to the Alertmanager.
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "127.0.0.1:12345"

# remote_write configuration is used by promxy as its local Appender, meaning all
# metrics promxy would "write" (not export) would be sent to this. Examples
# of this include: recording rules, metrics on alerting rules, etc.
remote_write:
  - url: http://localhost:8083/receive

##
### Promxy configuration
##
promxy:
  server_groups:
    # All upstream prometheus service discovery mechanisms are supported with the same
    # markup, all defined in https://github.com/prometheus/prometheus/blob/master/discovery/config/config.go#L33
    - static_configs:
        - targets:
          - localhost:9090
      # labels to be added to metrics retrieved from this server_group
      labels:
        sg: localhost_9090
      # anti-affinity for merging values in timeseries between hosts in the server_group
      anti_affinity: 10s
      # Controls whether to use remote_read or the prom HTTP API for fetching remote raw data
      remote_read: true
      # path_prefix defines a prefix to prepend to all queries to hosts in this servergroup
      path_prefix: /example/prefix
      # options for promxy's HTTP client when talking to hosts in server_groups
      http_client:
        # dial_timeout controls how long promxy will wait for a connection to the downstream
        # the default is 200ms.
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
      
      # relative_time_range defines a relative-to-now time range that this server group contains.
      # this is completely optional and start/end are both optional as well
      # an example is if this servergroup only has the most recent 3h of data 
      # the "start" would be -3h and the end would be left out
      relative_time_range:
        start: -3h
        end: -1h

      # absolute_time_range defines an absolute time range that this server group contains.
      # this is completely optional and start/end are both optional as well
      # and example is if the servergroup has been deprecated and is no longer receiving data
      # you could set the specific times that it has data for.
      absolute_time_range:
        start: 2009-10-10 23:00:00 +0000 UTC m=+0.000000001
        end: 2009-11-10 23:00:00 +0000 UTC m=+0.000000001

    # as many additional server groups as you have
    - static_configs:
        - targets:
          - localhost:9091
      labels:
        sg: localhost_9091
      anti_affinity: 10s
      http_client:
        tls_config:
          insecure_skip_verify: true
