##
## Regular prometheus configuration
##
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
- "*rule"

# Alerting specifies settings related to the Alertmanager.
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "127.0.0.1:12345"

# remote_write configuration is used by promxy as its local Appender, meaning all
# metrics promxy would "write" (not export) would be sent to this. Examples
# of this include: recording rules, metrics on alerting rules, etc.
remote_write:
  - url: http://localhost:8083/receive

##
### Promxy configuration
##
promxy:
  server_groups:
    - static_configs:
        - targets:
          - localhost:9090
      # labels to be added to metrics retrieved from this server_group
      labels:
        sg: localhost_9090
      # anti-affinity for merging values in timeseries between hosts in the server_group
      anti_affinity: 10s
      # options for promxy's HTTP client when talking to hosts in server_groups
      http_client:
        # dial_timeout controls how long promxy will wait for a connection to the downstream
        # the default is 200ms.
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
    # as many additional server groups as you have
    - static_configs:
        - targets:
          - localhost:9091
      labels:
        sg: localhost_9091
      anti_affinity: 10s
      http_client:
        tls_config:
          insecure_skip_verify: true
